# Generated by Django 4.2.17 on 2025-01-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_collection_owner_alter_paintscheme_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paintscheme',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
