# Generated by Django 4.2.17 on 2025-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_catalogue_notes_collection_notes_paintscheme_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
