# Generated by Django 4.2.17 on 2025-01-08 16:34

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_catalogue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[catalogue.models.Catalogue.validate_image]),
        ),
    ]
