# Generated by Django 4.2.17 on 2025-01-08 16:36

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_catalogue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='baseid',
            field=models.CharField(max_length=6, validators=[catalogue.models.Catalogue.validate_baseid]),
        ),
    ]
