# Generated by Django 4.2.17 on 2025-03-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_catalogue_baseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='paint',
        ),
        migrations.DeleteModel(
            name='PaintScheme',
        ),
    ]
